# Generated by Django 4.2.9 on 2024-02-07 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_assignment_course_notification_studentsummaryinfo_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SummaryInfo",
            new_name="TeacherSummaryInfo",
        ),
    ]
