# Generated by Django 4.2.9 on 2024-02-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_summaryinfo_teachersummaryinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
