# Generated by Django 4.2.9 on 2024-02-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_assignment_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
