# Generated by Django 4.2.9 on 2024-02-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_assignment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdashboarddata",
            name="notifications",
            field=models.ManyToManyField(
                related_name="student_dashboards", to="api.notification"
            ),
        ),
        migrations.AlterField(
            model_name="studentdashboarddata",
            name="summary_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_dashboard",
                to="api.studentsummaryinfo",
            ),
        ),
        migrations.AlterField(
            model_name="teacherdashboarddata",
            name="notifications",
            field=models.ManyToManyField(
                related_name="teacher_dashboards", to="api.notification"
            ),
        ),
        migrations.AlterField(
            model_name="teacherdashboarddata",
            name="summary_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_dashboard",
                to="api.teachersummaryinfo",
            ),
        ),
    ]
